# Generated by Django 4.2.16 on 2024-11-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='factory_yer',
            new_name='factory_year',
        ),
    ]
